//
// Created by Tanner on 4/10/2017.
//

#ifndef SOLID_PRINCIPLES_DENIALOFSERVICEANALYSER_H
#define SOLID_PRINCIPLES_DENIALOFSERVICEANALYSER_H


class DenialOfServiceAnalyser {

};


#endif //SOLID_PRINCIPLES_DENIALOFSERVICEANALYSER_H
