//
// Created by Tanner on 4/10/2017.
//

#ifndef SOLID_PRINCIPLES_PORTSCANANALYSERTESTER_H
#define SOLID_PRINCIPLES_PORTSCANANALYSERTESTER_H


class PortScanAnalyserTester {

};


#endif //SOLID_PRINCIPLES_PORTSCANANALYSERTESTER_H
